# Generated by Django 3.2.4 on 2021-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Apps',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Svas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Svas',
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocao', models.CharField(max_length=200, unique=True)),
                ('is_special', models.BooleanField(default=False)),
                ('special_text', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('speed', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('installments', models.PositiveIntegerField(default=0)),
                ('discount_description', models.CharField(max_length=200)),
                ('payment_code', models.CharField(max_length=3)),
                ('apps', models.ManyToManyField(blank=True, to='ofertas.Apps')),
                ('cities', models.ManyToManyField(blank=True, to='ofertas.Cities')),
                ('state', models.ManyToManyField(blank=True, to='ofertas.States')),
                ('svas', models.ManyToManyField(blank=True, to='ofertas.Svas')),
            ],
            options={
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
