# Generated by Django 3.2.4 on 2021-06-12 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocao', models.CharField(max_length=200, unique=True)),
                ('is_special', models.BooleanField(default=False)),
                ('special_text', models.CharField(default=None, max_length=200)),
                ('speed', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('installments', models.PositiveIntegerField(default=0)),
                ('discount_description', models.CharField(max_length=200)),
                ('payment_code', models.CharField(max_length=3)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citie', to='ofertas.cities')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='ofertas.states')),
            ],
        ),
    ]
