# Generated by Django 3.2.4 on 2021-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='cities',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='cities',
            field=models.ManyToManyField(to='ofertas.Cities'),
        ),
        migrations.RemoveField(
            model_name='ofertas',
            name='state',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='state',
            field=models.ManyToManyField(to='ofertas.States'),
        ),
    ]
