# Generated by Django 3.2.4 on 2021-06-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20210612_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Svas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, to='ofertas.Cities'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='special_text',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='state',
            field=models.ManyToManyField(blank=True, null=True, to='ofertas.States'),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='apps',
            field=models.ManyToManyField(blank=True, to='ofertas.Apps'),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='svas',
            field=models.ManyToManyField(blank=True, to='ofertas.Svas'),
        ),
    ]
