# Generated by Django 3.2.4 on 2021-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_auto_20210612_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apps',
            options={'verbose_name_plural': 'Apps'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='ofertas',
            options={'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='svas',
            options={'verbose_name_plural': 'Svas'},
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='cities',
            field=models.ManyToManyField(blank=True, to='ofertas.Cities'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='state',
            field=models.ManyToManyField(blank=True, to='ofertas.States'),
        ),
    ]
